language: python
python:
  - "2.6"
  - "2.7"
env:
  - KOTTI_TEST_DB_STRING=postgresql://postgres@localhost:5432/kotti_testing
  - KOTTI_TEST_DB_STRING=mysql+oursql://root@localhost:3306/kotti_testing
  - KOTTI_TEST_DB_STRING=sqlite://
install:
  - pip install https://github.com/disko/kotti/tarball/pytest_plugin
#  - pip install -r requirements.txt
  - python setup.py develop
  - python setup.py dev
  - pip install psycopg2 oursql
before_script:
  - psql -c 'create database kotti_testing;' -U postgres
  - mysql -e 'create database kotti_testing;'
script: py.test --tb=native --cov=kotti_media --cov-report=term-missing
notifications:
  irc: "irc.freenode.org#kotti"
